### ISSUE TITLE
package-selected-packages

### ISSUE THREAD

**Issue by ekenberg** [larstvei/Try#3]
Starting with Emacs 25.1 a custom list 'package-selected-packages' is automatically maintained in init.el whenever you install a package. Testing packages with 'Try' keeps adding to this list even though the packages are not permanently installed on the system. There are different opinions whether 'package-selected-packages' is a good thing or not, but regardless it seems wrong to have it fill up with not-installed packages.

http://endlessparentheses.com/new-in-package-el-in-emacs-25-1-user-selected-packages.html
http://irreal.org/blog/?p=5630

**Comment by larstvei** [comment]
Thank you! I was not aware of this feature, and you are of course completely right that Try should leave this list untouched.

I would greatly appreciate if you would verify the provided fix!

**Comment by ekenberg** [comment]
Got the last update from melpa and ran 'try 2048-game'. Result: everything else got removed from 'package-selected-packages' in init.el and it now contains just one entry: (2048-game) :rofl: 

Are you not running >= Emacs 25.1 or are you having trouble reproducing the issue? Let me know how I can help.

**Comment by larstvei** [comment]
Oh wow, that's not good. Sorry!

I'm running GNU Emacs 25.1.1 and had the same error, but 2046f58 worked for me. I don't allow any customizations to be written to init.el, så I only checked the value of `package-selected-packages` before and after using try, and it seemed to work fine. Apparently, the value of `package-selected-packages` is written to init.el when installing packages, so I didn't catch this. Thanks for detecting this so quick, I hope to find a fix very soon!

**Comment by larstvei** [comment]
Ok, hopefully 271b0a3 solves this.

What I did in the first (non)fix was to let `package-selected-packages` be bound locally, such that changes to it would remain local to the function (`try`). This was apparently written to file, which I did not detect.

Turns out that `package-install` provides an option to avoid the package to be added to the `package-selected-packages` list; this is toggled if the `emacs-version` is >=25.1.

Thanks for your help! It would be great if you could check out this fix too.

**Comment by ekenberg** [comment]
Good job fixing that so quickly, all seems to work now doing some quick tests! And thanks for providing 'try', it is very useful!

**Comment by larstvei** [comment]
Great to hear!

It's really good that you posted this issue; I would not have detected this bug myself.
