### ISSUE TITLE
Clean up the try* directory in /tmp

### ISSUE THREAD

**Issue by rieje** [larstvei/Try#7]
I was wondering why my `/tmp/` is polluted with so many `try*` directories--turns out that every time I start a new instance of Emacs, it creates a `try*` directory. When Emacs is closed, the directory remains. The directory should be removed if not needed.

**Comment by larstvei** [comment]
Your right! That's not pretty. I haven't noticed, because on macOS the path is pretty convoluted, so I would never accedentally end up there to observe it.

I'll try to find a fix ASAP.

**Comment by larstvei** [comment]
Ok, I hope this is better. Now a folder is created when you actually invoke `try`, not every time you launch a new instance of Emacs.

Thanks for reporting!
